name: 'Repo Validator'
description: 'Validates repository structure and other rules'
author: 'The Digital Defense Company'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  repo_token:
    description: 'GITHUB_TOKEN'
    required: true

runs:
  using: node20
  main: dist/index.js
